// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/maxblog-stats/internal/core"
	"github.com/liuzhaomax/maxblog-stats/src/api_stats_rpc/business"
	"github.com/liuzhaomax/maxblog-stats/src/api_stats_rpc/model"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	db, cleanup, err := core.InitDB()
	if err != nil {
		return nil, nil, err
	}
	modelStatsArticle := &model.ModelStatsArticle{
		DB: db,
	}
	trans := &core.Trans{
		DB: db,
	}
	client, cleanup2, err := core.InitRedis()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger := core.InitLogrus()
	coreLogger := &core.Logger{
		Logger: logger,
	}
	response := &core.Response{
		Logger: coreLogger,
	}
	rocketMQ := &core.RocketMQ{}
	businessStatsArticle := &business.BusinessStatsArticle{
		Model:    modelStatsArticle,
		Tx:       trans,
		Redis:    client,
		IRes:     response,
		RocketMQ: rocketMQ,
	}
	engine := core.InitGinEngine()
	registry := core.InitPrometheusRegistry()
	injector := &Injector{
		RPCService:         businessStatsArticle,
		Engine:             engine,
		DB:                 db,
		Redis:              client,
		PrometheusRegistry: registry,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
